= Contact {company name or product name} support

****
If you need more information about how to fill in this template, read the accompanying xref:./guide-contact-support.adoc[Contact Support guide].
****

****
This template includes writing instructions and boilerplate text that you can customize, use as-is, or completely replace with your own text. This text is indicated in {curly brackets}. Make sure you replace the placeholders with your own text.
****

{Write a hook to capture the attention of users and set a welcoming, friendly tone. For example, "Hi! How can we help you?".}

== Our products

{Product icon}

{Hyperlink to product's documentation or landing page here}[{Name and link to product page}]

[TIP]
If your company/organization has more than one product, consider placing the products and their hyperlinked information in a row.

== Support plans

{This section is optional. If support is only provided based on certain subscription levels or there are different tiers of support, indicate which subscription levels or plans come with support, possibly in table form.}

[cols="a,a"]
|===
| Free plan or basic license level | Pro plan or next license level

| Free
| {Cost per month/annually}

| * {First feature}
* {Second feature}
* {Third feature}
| * {First feature}
* {Second feature}
* {Third feature}
|===

== Contact details

{Delete any of the following sections that do not apply to your organization.}

=== Phone number

Our agents are available by phone at:

+x-xxx-xxx-xxxx

{Replace placeholder text with your phone support phone number}

Agents are available at {list available times and days that agents are available. For example: Mon-Fri x am-x pm time zone}

[TIP]
Hyperlink the support phone number for mobile users.

=== Text message

Text the {company name} support team at:

+x-xxx-xxx-xxxx

{Replace placeholder text with your text support phone number}

[TIP]
Hyperlink the support phone number for mobile users.

=== Email

Email us at:

{mailto:your-support-email@your-company-name.com[your-support-email@your-company-name.com]}

[TIP]
Hyperlink the email.

You can expect a response by {list maximum response times here. For example, within 24 hours}.

=== Live chat

Need a quick response? Chat with a support agent:

{link to chat url}[{Live chat}]

=== Social media

Connect with us on:

{X (Twitter)} at {link to social media url}[{@companysocialprofilename}]

{LinkedIn} at {https://www.linkedin.com/in/your-company-name/}

{Add additional social media accounts as needed.}

=== More support

Need more support? Check out these links below:

* {hyperlink to self-help options, such as community forums, Slack or Discord, or a knowledge base}

{Note that some companies might choose to put this section at the top of their contact support page in order to encourage users to solve problems on their own before contacting an agent.}

'''''

****
Explore https://github.com/anaxite/tgdp-asciidoc-templates[other converted templates] from The Good Docs Project, or browse https://thegooddocsproject.dev/[the originals^].
****
